### ISSUE TITLE
step do get

### ISSUE THREAD

**Issue by danilopolicarpos** [andreluaz/httparty#1]
Não tem nenhuma validação nessa feature você apenas está exibindo o body com o puts do Ruby.

 Entao("retorna a lista") do
    @retorno.body
    puts @retorno.body
    #puts "Nome: #{@retorno.nome}"
    #puts "Location: #{retorno.location}"
    #puts (@retorno.code)
  end

**Comment by andreluaz** [comment]
Incluso um expect para verificar se houve um retorno do body.
